version: "3.7"

services:
  uculqi:
    image: bregymr/uculqi
    ports:
      - 18000:18000
    secrets:
      - cert
      - key
    volumes:
      - ./uculqi.config.yml:/etc/uculqi/uculqi.config.yml
      - ./template.html:/etc/uculqi/template.html
secrets:
  cert:
    file: ./server.crt
  key:
    file: ./server.key
