// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/mculqi.proto

package mculqi

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Currency int32

const (
	Currency_PEN Currency = 0
	Currency_USD Currency = 1
)

var Currency_name = map[int32]string{
	0: "PEN",
	1: "USD",
}

var Currency_value = map[string]int32{
	"PEN": 0,
	"USD": 1,
}

func (x Currency) String() string {
	return proto.EnumName(Currency_name, int32(x))
}

func (Currency) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_05f5de1e4da6c1f4, []int{0}
}

type ChargeResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	At                   *timestamp.Timestamp `protobuf:"bytes,2,opt,name=at,proto3" json:"at,omitempty"`
	How                  float32              `protobuf:"fixed32,3,opt,name=how,proto3" json:"how,omitempty"`
	UserMessageFromCulqi string               `protobuf:"bytes,4,opt,name=userMessageFromCulqi,proto3" json:"userMessageFromCulqi,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ChargeResponse) Reset()         { *m = ChargeResponse{} }
func (m *ChargeResponse) String() string { return proto.CompactTextString(m) }
func (*ChargeResponse) ProtoMessage()    {}
func (*ChargeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f5de1e4da6c1f4, []int{0}
}

func (m *ChargeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChargeResponse.Unmarshal(m, b)
}
func (m *ChargeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChargeResponse.Marshal(b, m, deterministic)
}
func (m *ChargeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChargeResponse.Merge(m, src)
}
func (m *ChargeResponse) XXX_Size() int {
	return xxx_messageInfo_ChargeResponse.Size(m)
}
func (m *ChargeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChargeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChargeResponse proto.InternalMessageInfo

func (m *ChargeResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChargeResponse) GetAt() *timestamp.Timestamp {
	if m != nil {
		return m.At
	}
	return nil
}

func (m *ChargeResponse) GetHow() float32 {
	if m != nil {
		return m.How
	}
	return 0
}

func (m *ChargeResponse) GetUserMessageFromCulqi() string {
	if m != nil {
		return m.UserMessageFromCulqi
	}
	return ""
}

type ChargeParams struct {
	UserInfo             *UserInformation `protobuf:"bytes,1,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	Amount               float32          `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             Currency         `protobuf:"varint,3,opt,name=currency,proto3,enum=culqi.Currency" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ChargeParams) Reset()         { *m = ChargeParams{} }
func (m *ChargeParams) String() string { return proto.CompactTextString(m) }
func (*ChargeParams) ProtoMessage()    {}
func (*ChargeParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f5de1e4da6c1f4, []int{1}
}

func (m *ChargeParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChargeParams.Unmarshal(m, b)
}
func (m *ChargeParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChargeParams.Marshal(b, m, deterministic)
}
func (m *ChargeParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChargeParams.Merge(m, src)
}
func (m *ChargeParams) XXX_Size() int {
	return xxx_messageInfo_ChargeParams.Size(m)
}
func (m *ChargeParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ChargeParams.DiscardUnknown(m)
}

var xxx_messageInfo_ChargeParams proto.InternalMessageInfo

func (m *ChargeParams) GetUserInfo() *UserInformation {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *ChargeParams) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ChargeParams) GetCurrency() Currency {
	if m != nil {
		return m.Currency
	}
	return Currency_PEN
}

type UserInformation struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	CountryCode          string   `protobuf:"bytes,5,opt,name=countryCode,proto3" json:"countryCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInformation) Reset()         { *m = UserInformation{} }
func (m *UserInformation) String() string { return proto.CompactTextString(m) }
func (*UserInformation) ProtoMessage()    {}
func (*UserInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f5de1e4da6c1f4, []int{2}
}

func (m *UserInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInformation.Unmarshal(m, b)
}
func (m *UserInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInformation.Marshal(b, m, deterministic)
}
func (m *UserInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInformation.Merge(m, src)
}
func (m *UserInformation) XXX_Size() int {
	return xxx_messageInfo_UserInformation.Size(m)
}
func (m *UserInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInformation.DiscardUnknown(m)
}

var xxx_messageInfo_UserInformation proto.InternalMessageInfo

func (m *UserInformation) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UserInformation) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInformation) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserInformation) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserInformation) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func init() {
	proto.RegisterEnum("culqi.Currency", Currency_name, Currency_value)
	proto.RegisterType((*ChargeResponse)(nil), "culqi.ChargeResponse")
	proto.RegisterType((*ChargeParams)(nil), "culqi.ChargeParams")
	proto.RegisterType((*UserInformation)(nil), "culqi.UserInformation")
}

func init() { proto.RegisterFile("grpc/mculqi.proto", fileDescriptor_05f5de1e4da6c1f4) }

var fileDescriptor_05f5de1e4da6c1f4 = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xc1, 0xcb, 0xd3, 0x30,
	0x1c, 0xfd, 0xd2, 0xb9, 0xda, 0xfe, 0x26, 0xfb, 0x66, 0xfc, 0x1c, 0xa5, 0x0c, 0x2c, 0x3d, 0x8d,
	0x09, 0x1d, 0x54, 0xf0, 0x2c, 0x56, 0x05, 0x0f, 0x1b, 0x23, 0xba, 0x8b, 0xb7, 0xac, 0xcb, 0xba,
	0x62, 0xd3, 0xd4, 0x24, 0x45, 0xf6, 0x17, 0x78, 0xf7, 0xe6, 0x7f, 0x2b, 0x4d, 0xda, 0x39, 0xc5,
	0x5b, 0xde, 0xfb, 0x3d, 0xde, 0xef, 0xe5, 0x25, 0xf0, 0xb4, 0x90, 0x4d, 0xbe, 0xe6, 0x79, 0x5b,
	0x7d, 0x2b, 0x93, 0x46, 0x0a, 0x2d, 0xf0, 0xd8, 0x80, 0xf0, 0x45, 0x21, 0x44, 0x51, 0xb1, 0xb5,
	0x21, 0x0f, 0xed, 0x69, 0xad, 0x4b, 0xce, 0x94, 0xa6, 0xbc, 0xb1, 0xba, 0xf8, 0x27, 0x82, 0x69,
	0x76, 0xa6, 0xb2, 0x60, 0x84, 0xa9, 0x46, 0xd4, 0x8a, 0xe1, 0x29, 0x38, 0xe5, 0x31, 0x40, 0x11,
	0x5a, 0xfa, 0xc4, 0x29, 0x8f, 0x78, 0x05, 0x0e, 0xd5, 0x81, 0x13, 0xa1, 0xe5, 0x24, 0x0d, 0x13,
	0x6b, 0x98, 0x0c, 0x86, 0xc9, 0xe7, 0xc1, 0x90, 0x38, 0x54, 0xe3, 0x19, 0x8c, 0xce, 0xe2, 0x7b,
	0x30, 0x8a, 0xd0, 0xd2, 0x21, 0xdd, 0x11, 0xa7, 0xf0, 0xd0, 0x2a, 0x26, 0x37, 0x4c, 0x29, 0x5a,
	0xb0, 0x0f, 0x52, 0xf0, 0xac, 0x4b, 0x16, 0x3c, 0x32, 0xfe, 0xff, 0x9d, 0xc5, 0x3f, 0x10, 0x3c,
	0xb1, 0xa1, 0x76, 0x54, 0x52, 0xae, 0x70, 0x0a, 0x5e, 0x27, 0xfc, 0x58, 0x9f, 0x84, 0x09, 0x36,
	0x49, 0xe7, 0x89, 0xbd, 0xed, 0xbe, 0xa7, 0x25, 0xa7, 0xba, 0x14, 0x35, 0xb9, 0xea, 0xf0, 0x1c,
	0x5c, 0xca, 0x45, 0x5b, 0xdb, 0xe8, 0x0e, 0xe9, 0x11, 0x7e, 0x09, 0x5e, 0xde, 0x4a, 0xc9, 0xea,
	0xfc, 0x62, 0x72, 0x4e, 0xd3, 0xfb, 0xde, 0x2b, 0xeb, 0x69, 0x72, 0x15, 0xc4, 0xbf, 0x10, 0xdc,
	0xff, 0xb3, 0x02, 0x3f, 0xc0, 0x58, 0x8b, 0xaf, 0xac, 0xee, 0x2b, 0xb2, 0xa0, 0x63, 0x19, 0xa7,
	0x65, 0x65, 0xb6, 0xf9, 0xc4, 0x02, 0xbc, 0x00, 0xff, 0x54, 0x4a, 0xa5, 0xb7, 0x94, 0x33, 0xb3,
	0xcd, 0x27, 0x7f, 0x08, 0x1c, 0x82, 0x57, 0xd1, 0x7e, 0x68, 0xfb, 0xb8, 0x62, 0x1c, 0xc1, 0x24,
	0xef, 0xf2, 0xca, 0x4b, 0x26, 0x8e, 0x2c, 0x18, 0x9b, 0xf1, 0x2d, 0xb5, 0x5a, 0x80, 0x37, 0x24,
	0xc6, 0x8f, 0x61, 0xb4, 0x7b, 0xbf, 0x9d, 0xdd, 0x75, 0x87, 0xfd, 0xa7, 0x77, 0x33, 0x94, 0xbe,
	0x01, 0x77, 0x63, 0xda, 0xc4, 0xaf, 0xc1, 0xb5, 0x65, 0xe2, 0x67, 0xc3, 0x45, 0x6f, 0xba, 0x0d,
	0x9f, 0xff, 0x45, 0x0e, 0xbf, 0x20, 0xbe, 0x7b, 0xeb, 0x7d, 0x71, 0xed, 0x97, 0x3a, 0xb8, 0xe6,
	0xb5, 0x5f, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x32, 0xac, 0x59, 0x1b, 0x68, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MCulqiClient is the client API for MCulqi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MCulqiClient interface {
	Charge(ctx context.Context, in *ChargeParams, opts ...grpc.CallOption) (*ChargeResponse, error)
}

type mCulqiClient struct {
	cc *grpc.ClientConn
}

func NewMCulqiClient(cc *grpc.ClientConn) MCulqiClient {
	return &mCulqiClient{cc}
}

func (c *mCulqiClient) Charge(ctx context.Context, in *ChargeParams, opts ...grpc.CallOption) (*ChargeResponse, error) {
	out := new(ChargeResponse)
	err := c.cc.Invoke(ctx, "/culqi.MCulqi/Charge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MCulqiServer is the server API for MCulqi service.
type MCulqiServer interface {
	Charge(context.Context, *ChargeParams) (*ChargeResponse, error)
}

func RegisterMCulqiServer(s *grpc.Server, srv MCulqiServer) {
	s.RegisterService(&_MCulqi_serviceDesc, srv)
}

func _MCulqi_Charge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChargeParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCulqiServer).Charge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/culqi.MCulqi/Charge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCulqiServer).Charge(ctx, req.(*ChargeParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _MCulqi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "culqi.MCulqi",
	HandlerType: (*MCulqiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Charge",
			Handler:    _MCulqi_Charge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/mculqi.proto",
}
